<a href="https://colab.research.google.com/github/sarthak572/cognitive_computing/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
data = {
    "refund" :['yes','No','No','No','No','No','No','No','yes','yes'],
    "marital":['single','married','single','single','single','single','single','married','single','single'],
    "taxable_income":[120,200,100,1000,300,400,700,200,600,900],
    "cheat":['yes','no','yes','yes','yes','no','yes','no','no','yes']
}
df = pd.DataFrame(data)
print(df)

  refund  marital  taxable_income cheat
0    yes   single             120   yes
1     No  married             200    no
2     No   single             100   yes
3     No   single            1000   yes
4     No   single             300   yes
5     No   single             400    no
6     No   single             700   yes
7     No  married             200    no
8    yes   single             600    no
9    yes   single             900   yes

In [ ]:
print(df.loc[0])

refund               yes
marital           single
taxable_income       120
cheat                yes
Name: 0, dtype: object

In [ ]:
print(df.loc[3:7])

  refund  marital  taxable_income cheat
3     No   single            1000   yes
4     No   single             300   yes
5     No   single             400    no
6     No   single             700   yes
7     No  married             200    no

In [ ]:
print(df.iloc[4:8,2:4])

   taxable_income cheat
4             300   yes
5             400    no
6             700   yes
7             200    no

In [ ]:
import pandas as pd
from sklearn.datasets import load_iris


iris = load_iris()

In [ ]:
df = pd.DataFrame(iris.data, columns=iris.feature_names)
print(df)

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [ ]:
df.iloc[0:2 , 0:3]

   sepal length (cm)  petal length (cm)  petal width (cm)
0                5.1                1.4               0.2
1                4.9                1.4               0.2

In [ ]:
df.loc[3:4]

   sepal length (cm)  petal length (cm)  petal width (cm)
3                4.6                1.5               0.2
4                5.0                1.4               0.2

In [ ]:
df.drop('sepal width (cm)', axis=1 , inplace = True)

In [ ]:
df

     sepal length (cm)  petal length (cm)  petal width (cm)
0                  5.1                1.4               0.2
1                  4.9                1.4               0.2
2                  4.7                1.3               0.2
3                  4.6                1.5               0.2
4                  5.0                1.4               0.2
..                 ...                ...               ...
145                6.7                5.2               2.3
146                6.3                5.0               1.9
147                6.5                5.2               2.0
148                6.2                5.4               2.3
149                5.9                5.1               1.8

[150 rows x 3 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 3 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   sepal length (cm)  150 non-null    float64
 1   petal length (cm)  150 non-null    float64
 2   petal width (cm)   150 non-null    float64
dtypes: float64(3)
memory usage: 3.6 KB

In [ ]:
df.describe()

       sepal length (cm)  petal length (cm)  petal width (cm)
count         150.000000         150.000000        150.000000
mean            5.843333           3.758000          1.199333
std             0.828066           1.765298          0.762238
min             4.300000           1.000000          0.100000
25%             5.100000           1.600000          0.300000
50%             5.800000           4.350000          1.300000
75%             6.400000           5.100000          1.800000
max             7.900000           6.900000          2.500000